[package]
name = "rust-directory-lister"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vw"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
walkdir = "2"
chrono = "0.4"
